### PR TITLE
Upgrade cover alls version4

### PR DESCRIPTION
**Pull request by pgrosu**

### CODE REVIEW

**Comment by deflaux** [comment]
please be sure to sign the CLA @pgrosu , thanks!

**Comment by pgrosu** [comment]
@deflaux Unfortunately I cannot sign it as neither case solely applies to me, which is why I've been only posting and providing testing for the past two years, since the inception of GoogleGenomics.  Not sure if you saw this previous discussion regarding the reason, as both cases apply to me and are inseparable, and thus there is no CLA for that situation:

https://github.com/googlegenomics/spark-examples/pull/36#issuecomment-59432941

Hope it makes sense,
Paul

**Comment by deflaux** [comment]
@pgrosu many people are both an individual and at a company.  In general, what those people do is ask their company if they may patch particular github repositories in their spare time.  If their company agrees, then they sign the individual CLA since the patching is occurring as an individual.

Then we will see you listed [here](https://github.com/googlegenomics/linkage-disequilibrium/graphs/contributors)!

**Comment by pgrosu** [comment]
@deflaux In theory that sounds practical, but in practice that can become quite a political bottleneck.  Sometimes discovering how to provide maximum help has been forged over many years of painful experiences.

Being on the contributors list here would be nice, but I also contribute to many other places :)

**Comment by pgrosu** [comment]
Hopefully together we can take GoogleGenomics to the next level, and make it more prolific so that we can bring in more folks on board.  It's been too quiet for too long, and these projects have huge untapped potential that can help the community immensely.

**Comment by deflaux** [comment]
Thank you for trying to help @pgrosu but we cannot look at this pull request without a CLA.  Please continue to follow the guidance Cassie gave you earlier.

**Comment by pgrosu** [comment]
Hi Nicole,

It was just a temporary PR to just troubleshoot what might be happening - it was not meant for merging.  That's the reason I just stick to posting comments, and sometimes triggering builds to just troubleshoot the issues, and then closing them afterwards.

Thanks,
Paul

**Pull request closed without merging**
