### PR TITLE
Consolidate running instructions in RTD.

### PR DESCRIPTION
**Pull request by deflaux**

### CODE REVIEW

**Comment by deflaux** [comment]
Fixes https://github.com/googlegenomics/linkage-disequilibrium/issues/4

**Comment by cmclean** [comment]
Based on the modifications to the pipelines (referencing RTD rather than including pipeline commands as comments), the README.md should have the two lines "An example command to run the pipeline is given within the {WriteLdBigtable,QueryLdBigtable}.java source code itself." updated to point to the RTD areas as well.

**Comment by deflaux** [comment]
Modified README.md.  PTAL @cmclean

**Comment by pouyak** [comment]
LGTM

**Pull request merged**
